# Generated by Django 2.1.5 on 2019-01-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsdata',
            name='batch_id',
        ),
    ]
