# Generated by Django 2.1.5 on 2019-01-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_remove_documentsdata_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdata',
            name='batch_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
